#!/bin/bash
#SBATCH --job-name=discrete_motion
#SBATCH --output=dm.o
#SBATCH --error=dm.error

#SBATCH --partition=savio3
#SBATCH --time=24:00:00
#SBATCH --nodes=12
#SBATCH --ntasks-per-node=1
#SBATCH--cpus-per-task=32

# QoS: savio_normal
#SBATCH --qos=savio_normal
#
# Account:
#SBATCH -A fc_neutronics

# run command
#rm -rf bumat_files/ waste/ temporary_files/
mpirun -np $SLURM_JOB_NUM_NODES --map-by ppr:$SLURM_TASKS_PER_NODE:node:pe=$SLURM_CPUS_PER_TASK /global/home/users/yvesrobert/serpent_pseudo_motion_2.1.32/sss2 -omp $SLURM_CPUS_PER_TASK input
